# Generated by Django 3.2.3 on 2021-05-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='membership_type',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Basic', 'Basic'), ('Enterprice', 'Enterprice')], default='Basic', max_length=30),
        ),
    ]
